FROM debian:bookworm

MAINTAINER Ivan Alonso <kaian@irontec.com>

RUN apt-get update && apt-get install -y dpkg-dev debhelper git make golang libpcap-dev libc6-dev libdbus-1-dev libsystemd-dev

# Create jenkins user (configurable)
ARG UNAME=jenkins
ARG UID=108
ARG GID=117
RUN groupadd -g $GID $UNAME
RUN useradd -m -u $UID -g $GID -s /bin/bash $UNAME
RUN mkdir -p /build/source
RUN chown -R jenkins.jenkins /build/

WORKDIR /build/source